### ISSUE TITLE
403 missing

### ISSUE THREAD

**Issue by HendrikGematik** [gematik/api-dipag#1]
In https://github.com/gematik/api-erg/blob/2f9fbc9d241df4a653f7960b33850b88d540cb13/swagger.yaml#L130 ist nur 401 (kein Token) angegeben.
Wenn jeder für jeden eine Berechtigung eintragen darf, dann ist alles gut, wenn aber der Scope permission.c (oder so ähnlich) fehlt, dann müsste hier noch 403 aufgelistet werden?

**Comment by cybernop** [comment]
wurde hinzugefügt
