### ISSUE TITLE
#ref defitnitions missing

### ISSUE THREAD

**Issue by HendrikGematik** [gematik/api-dipag#2]
https://github.com/gematik/api-erg/blob/2f9fbc9d241df4a653f7960b33850b88d540cb13/swagger.yaml#L178

Wie sind die Strukturen von permissions und status?
application/json ist als type angegeben aber am Ende des swagger-files sind keine referenzierten definitions zu finden.

**Comment by cybernop** [comment]
Die definitions befinden sich am Anfang der Datei
